# This is a config file with the general options for DEBUG
# a comment

#----------------------------------------------------------------------------------------------------------------
exp_name: train
exp_group: profile
seed_mode: balanced     # ['balanced', 'random']
seed: 5678
mode: train             # ['train', 'valid', 'eval']
debug: false
logging_dir: './logging'
wandb: false

num_iters: 5000
batch_size: 32
num_workers: 0
print_every: 100
logging_interval: 500
lr: 1e-4
lr_scheduler_step: 500
lr_min: 1e-7
lr_decay_rate: 0.9
lr_patience_times: 3

#----------------------------------------------------------------------------------------------------------------
model: crnn10           # ['crnn10', 'samplecnn', 'samplecnn_gru']
model_features_transform: stft_iv     # ['stft_iv', 'none']
model_augmentation: false
model_rotations: True
model_loss_fn: mse      # ['mse', 'bce']
model_normalization: batchnorm
detection_threshold: 0.4
thresh_unify: 15
use_mixup: true
mixup_alpha: 0.2
input_shape: [7, 96, 256]      # 'input_shape': [4, 144000], when using sample cnn
output_shape: [3, 12, 256]

#----------------------------------------------------------------------------------------------------------------
dataset_chunk_size_seconds: 2.55  # For example 1.27, or 2.55.
dataset_chunk_mode: random        # ['random', 'fixed', 'full']
dataset_multi_track: false
dataset_backend: sony
dataset_trim_wavs: -1
dataset_root: ['/m/triton/scratch/work/falconr1/sony/data_dcase2022']
dataset_list_train: ['dcase2022_devtrain_all.txt']
dataset_root_valid: '/m/triton/scratch/work/falconr1/sony/data_dcase2022'
dataset_list_valid: 'dcase2022_devtest_debug.txt'
dataset_root_eval: '/m/triton/scratch/work/falconr1/sony/data_dcase2022'
dataset_list_eval: 'dcase2022_eval_all.txt'

#----------------------------------------------------------------------------------------------------------------
evaluation_overlap_fraction: 1
