# This is a config file with the general options for DEBUG
# a comment

#----------------------------------------------------------------------------------------------------------------
# Experiment metadata
exp_name: debug
exp_group: 'debug'
seed_mode: balanced     # ['balanced', 'random']
seed: 1234
mode: train             # ['train', 'valid', 'eval']
debug: true
profiling: false
logging_dir: './logging'
wandb: false
oracle_mode: false

#----------------------------------------------------------------------------------------------------------------
# Training
num_iters: 200
batch_size: 2
num_workers: 0
print_every: 50
logging_interval: 100
solver: DAN  # ['DAN', 'vanilla']
disc_algorithm: vanilla

# Predictor
G_crit: ls
lr: 1e-4
lr_scheduler_step: 1000
lr_min: 1e-7
lr_decay_rate: 0.9
lr_patience_times: 3
w_rec: 100
w_adv: 0

# Discriminator
D_crit: ls # choices=['minmax', 'non-sat', 'ls', 'wass', 'hinge']
D_lr: 1e-1
D_lr_min: 1e-7
D_lr_decay_rate: 0.9
D_lr_patience_times: 3
D_lr_weight_decay: 0.001
D_lr_scheduler: lrstep
D_lr_scheduler_step: 10
D_lr_scheduler_T_0: 200
D_lr_scheduler_T_mult: 1
D_batches: 0
D_grad_clip: 10
curriculum_D_threshold_min: 0.0
curriculum_D_threshold_max: 0.0
curriculum_w_adv: 0.0

# Scheduler
curriculum_scheduler: linear


#----------------------------------------------------------------------------------------------------------------
# Models

# Predictor
model: crnn10           # ['crnn10', 'samplecnn', 'samplecnn_gru']
model_features_transform: stft_iv     # ['stft_iv', 'mel_iv', 'mel_base', 'none']
model_spatialmixup: false
model_augmentation: false
model_spec_augmentation: false
model_rotations: false
model_rotations_mode: azi
model_rotations_noise: false
model_loss_fn: mse      # ['mse', 'bce']
model_normalization: batchnorm
detection_threshold: 0.4
thresh_unify: 15
use_mixup: false
mixup_alpha: 0.2
input_shape: [7, 256, 256]      # 'input_shape': [4, 144000], when using sample cnn
output_shape: [3, 12, 256]

# Discriminator
disc: DiscriminatorModularThreshold
disc_input_shape:  [3, 256, 256]      # These are labels, or upsampled labels, or conditioned-upsampled labels
disc_feature_maps: 64
disc_final: none
disc_kernels: ["4,4", "4,4", "4,4", "4,4", "2,2"]
disc_strides: ["2,2", "2,2", "4,4", "4,4", "2,2"]
disc_padding: [1, 1, 1, 1, 0]
disc_normalization: instance
disc_block: coord
disc_conditioning: none-upsample
disc_final_multi: 4
disc_threshold_min: 0.3
disc_threshold_max: 1.5
disc_use_spectral_norm: true
disc_use_threshold_norm: true
disc_use_threshold_binarize: false
disc_use_low_pass: false
disc_with_r: false
disc_freq_pooling: none


#----------------------------------------------------------------------------------------------------------------
# Dataset
dataset_chunk_size_seconds: 2.55  # For example 1.27, or 2.55.
dataset_chunk_mode: random        # ['random', 'fixed', 'full']
dataset_multi_track: false
dataset_backend: sony
dataset_ignore_pad_labels: false
dataset_trim_wavs: -1
dataset_root: ['/m/triton/work/falconr1/sony/data_dcase2022']  # '/m/triton/scratch/work/falconr1/sony/data_dcase2022'
dataset_list_train: ['dcase2022_devtrain_debug.txt']
dataset_root_valid: '/m/triton/work/falconr1/sony/data_dcase2022'
dataset_list_valid: 'dcase2022_devtrain_debug.txt'
dataset_root_eval: '/m/triton/work/falconr1/sony/data_dcase2022'
dataset_list_eval: 'dcase2022_eval_all.txt'

#----------------------------------------------------------------------------------------------------------------
# Evaluation
evaluation_overlap_fraction: 1
